package com.probase.reservationticketingwebservice.enumerations;

public enum ServiceType {

	CARD_PURCHASE, 
	CARD_DEBIT,
	CARD_CREDIT,
	TRANSACTION_REVERSAL,
	CASH_PAYMENT, 
	CASH_COLLECT_FOR_TRIP,
	EPAYMENT_FOR_TRIP,
	WALLET_CREDIT,
	WALLET_DEBIT, 
	ASSIGN_CARD_TO_VENDOR, 
	ASSIGN_CARD_TO_CUSTOMER, 
	CARD_FUND, 
	CARD_YEARLY_FEE, 
	CASH_COLLECT_FOR_SHIPMENT,
	CASH_REFUND_FOR_TRIP, CASH_SURCHARGE
			
}
